import DOMPurify from "dompurify";
import { buildAuroraSheet } from "@/lib/aurora-sheet";
import { ArrowLeftIcon, DownloadIcon, FileTextIcon, PrinterIcon } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Link, useParams } from "react-router-dom";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import { spellLevelLine, useSheetData, type Proficiency, type SheetData, type SheetFeature, type SheetSpell, type SheetSpellcasting } from "@/lib/api/sheet";
import { cn } from "@/lib/utils";

/*
 * The character sheet in the layout Aurora prints: main page, details, inventory, notes, spellcasting and spell
 * cards. Pages are US Letter at 96 dpi (816 × 1056 px); "Download PDF" makes Aurora's own sheet (lib/aurora-sheet).
 */

const PAGE = "sheet-page relative mx-auto mb-8 h-[1056px] w-[816px] overflow-hidden bg-white p-9 text-black shadow-lg print:mb-0 print:shadow-none";
const fmt = (n: number) => (n >= 0 ? `+${n}` : `${n}`);

function Label({ children, className }: { children: ReactNode; className?: string }) {
  return <div className={cn("text-[7.5px] font-semibold uppercase tracking-wider text-neutral-600", className)}>{children}</div>;
}

function Frame({ label, children, className, labelPosition = "bottom" }: { label?: string; children?: ReactNode; className?: string; labelPosition?: "top" | "bottom" }) {
  return (
    <div className={cn("relative flex flex-col rounded-lg border-2 border-neutral-800 bg-white px-2.5 py-2", className)}>
      {label && labelPosition === "top" && <Label className="mb-1">{label}</Label>}
      <div className="min-h-0 flex-1 overflow-hidden">{children}</div>
      {label && labelPosition === "bottom" && <Label className="mt-1 text-center">{label}</Label>}
    </div>
  );
}

function Pill({ children, className }: { children: ReactNode; className?: string }) {
  return <div className={cn("rounded-md bg-neutral-100 px-2 py-0.5 text-[10px]", className)}>{children}</div>;
}

function Dot({ proficiency }: { proficiency: Proficiency }) {
  return (
    <span className="inline-flex size-2.5 shrink-0 items-center justify-center rounded-full border border-neutral-700">
      {proficiency !== "none" && <span className={cn("rounded-full bg-neutral-800", proficiency === "expertise" ? "size-2" : "size-1.5")} />}
    </span>
  );
}

function FeatureText({ features }: { features: SheetFeature[] }) {
  return (
    <div className="space-y-1.5 text-[8.5px] leading-[1.3]">
      {features.map((f) => (
        <p key={f.title}>
          <b className="italic">
            {f.title}
            {f.usage || f.action ? ` (${[f.action, f.usage].filter(Boolean).join(", ")})` : ""}.
          </b>{" "}
          {f.text}
        </p>
      ))}
    </div>
  );
}

// how much feature text fits in a box before the rest continues on an extra page
function split(features: SheetFeature[], budget: number): [SheetFeature[], SheetFeature[]] {
  let used = 0;
  const index = features.findIndex((f) => (used += f.title.length + f.text.length + 60) > budget);
  return index < 0 ? [features, []] : [features.slice(0, index), features.slice(index)];
}

function Header({ data, fields }: { data: SheetData; fields: [string, string, string?][] }) {
  return (
    <div className="mb-4 grid grid-cols-[38%_1fr] gap-3">
      <div className="flex flex-col justify-end">
        <div className="rounded-md border-2 border-neutral-800 px-3 py-2 text-center text-xl">{data.name}</div>
        <Label className="mt-1 pl-2">Character name</Label>
      </div>
      <div className="grid grid-cols-4 gap-x-3 gap-y-1.5 rounded-lg border-2 border-neutral-800 px-3 py-2">
        {fields.map(([label, value, span]) => (
          <div key={label} className={cn("min-w-0", span)}>
            <div className="truncate border-b border-neutral-400 text-[11px] leading-5">{value || " "}</div>
            <Label>{label}</Label>
          </div>
        ))}
      </div>
    </div>
  );
}

function Footer() {
  return <p className="absolute inset-x-0 bottom-3 text-center text-[7px] text-neutral-500">This character sheet was generated by Starlights, with content from Aurora Legacy.</p>;
}

function MainPage({ data, features }: { data: SheetData; features: SheetFeature[] }) {
  const s = data.story;
  return (
    <div className={PAGE}>
      <Header
        data={data}
        fields={[
          ["Character level, species & class", data.classLine, "col-span-3"],
          ["Experience", s.experience ?? ""],
          ["Background", data.background],
          ["Alignment", data.alignment],
          ["Deity", data.deity],
          ["Player name", data.player],
        ]}
      />

      <div className="grid h-[870px] grid-cols-3 gap-3">
        {/* abilities, saves, skills */}
        <div className="flex flex-col gap-2">
          <div className="flex flex-1 gap-2 rounded-lg bg-neutral-200 p-2">
            <div className="flex w-[68px] flex-col justify-between">
              {data.abilities.map((a) => (
                <div key={a.abbreviation} className="flex flex-col items-center rounded-lg border-2 border-neutral-800 bg-white pb-1.5 pt-1">
                  <Label>{a.name}</Label>
                  <div className="text-2xl leading-8">{a.calculatedScore}</div>
                  <div className="-mb-3 rounded-full border-2 border-neutral-800 bg-white px-2.5 text-[12px]">{fmt(a.calculatedModifier)}</div>
                </div>
              ))}
            </div>
            <div className="flex min-w-0 flex-1 flex-col gap-2">
              <div className="flex items-center gap-2 rounded-md border-2 border-neutral-800 bg-white px-2 py-1">
                <Label className="flex-1">Proficiency bonus</Label>
                <span className="rounded-full border-2 border-neutral-800 px-2 text-sm">{fmt(data.proficiencyBonus)}</span>
              </div>
              <Frame label="Saving throws">
                {data.saves.map((save) => (
                  <div key={save.name} className="flex items-center gap-1.5 text-[9.5px] leading-[15px]">
                    <Dot proficiency={save.proficiency} />
                    <span className="w-5 text-right">{fmt(save.calculatedBonus)}</span>
                    <span>{save.name.replace(" Saving Throw", "")}</span>
                  </div>
                ))}
              </Frame>
              <Frame label="Skills" className="flex-1">
                {data.skills.map((skill) => (
                  <div key={skill.name} className="flex items-center gap-1 text-[8.8px] leading-[15.5px]">
                    <Dot proficiency={skill.proficiency} />
                    <span className="w-5 text-right">{fmt(skill.calculatedBonus)}</span>
                    <span className="truncate">
                      {skill.name} <span className="text-neutral-500">({skill.abilityScoreAbbreviation[0]}{skill.abilityScoreAbbreviation.slice(1).toLowerCase()})</span>
                    </span>
                  </div>
                ))}
              </Frame>
              <div className="flex items-center gap-2 rounded-md border-2 border-neutral-800 bg-white px-2 py-1">
                <span className="rounded border border-neutral-800 px-1.5 text-sm">{data.passivePerception}</span>
                <Label>Passive perception</Label>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2 rounded-lg border-2 border-neutral-800 px-2 py-1.5">
            <Label>Initiative</Label>
            <span className="rounded-full border-2 border-neutral-800 px-2.5 text-lg">{fmt(data.initiative)}</span>
          </div>
        </div>

        {/* combat */}
        <div className="flex flex-col gap-2">
          <Frame label="Armor class">
            <div className="flex items-start gap-2">
              <div className="flex-1 space-y-1">
                <Label>Armor</Label>
                <Pill>Unarmored</Pill>
                <Label>Shield</Label>
                <Pill>&nbsp;</Pill>
              </div>
              <div className="flex h-16 w-14 flex-col items-center justify-center rounded-b-[26px] rounded-t-md border-2 border-neutral-800">
                <div className="text-2xl leading-7">{data.armorClass}</div>
                <Label>AC</Label>
              </div>
            </div>
          </Frame>
          <Frame label="Current hit points" className="h-[120px]">
            <div className="grid grid-cols-3 gap-2 text-center">
              {[
                ["Maximum", data.hitPoints ?? ""],
                ["Hit dice", data.hitDice],
                ["Temporary", ""],
              ].map(([label, value]) => (
                <div key={label as string}>
                  <Label>{label}</Label>
                  <Pill>{value || " "}</Pill>
                </div>
              ))}
            </div>
            <div className="mt-6 flex justify-between px-2 text-[7px] uppercase text-neutral-500">
              <span>○ ○ ○ death save successes</span>
              <span>death save failures ○ ○ ○</span>
            </div>
          </Frame>
          <Frame label="Speed, senses & conditions">
            <div className="grid grid-cols-4 gap-1.5 text-center">
              {(["walk", "fly", "climb", "swim"] as const).map((k) => (
                <div key={k}>
                  <Label>{k === "walk" ? "Speed" : k}</Label>
                  <Pill>{data.speeds[k]}ft.</Pill>
                </div>
              ))}
              <div className="col-span-2">
                <Label>Vision</Label>
                <Pill>{data.vision.join(", ") || " "}</Pill>
              </div>
              <div>
                <Label>Inspiration</Label>
                <Pill>&nbsp;</Pill>
              </div>
              <div>
                <Label>Exhaustion</Label>
                <Pill>&nbsp;</Pill>
              </div>
            </div>
          </Frame>
          <Frame label="Species traits" className="flex-1">
            <FeatureText features={data.speciesTraits} />
          </Frame>
        </div>

        {/* features, proficiencies */}
        <div className="flex flex-col gap-2">
          <Frame label="Features & traits" className="flex-1">
            <FeatureText features={features} />
          </Frame>
          <Frame label="Proficiencies & languages" className="h-[210px]">
            <div className="space-y-1.5 text-[8.5px] leading-[1.3]">
              {[
                ["Armor Proficiencies", data.proficiencies.armor],
                ["Weapon Proficiencies", data.proficiencies.weapons],
                ["Tool Proficiencies", data.proficiencies.tools],
                ["Languages", data.languages],
              ].map(([label, list]) =>
                (list as string[]).length ? (
                  <p key={label as string}>
                    <b className="italic">{label}.</b> {(list as string[]).join(", ")}
                  </p>
                ) : null,
              )}
            </div>
          </Frame>
        </div>
      </div>
      <Footer />
    </div>
  );
}

function DetailsPage({ data }: { data: SheetData }) {
  const s = data.story;
  const box = (label: string, value: string | undefined, className?: string) => (
    <Frame label={label} className={className}>
      <p className="whitespace-pre-line text-[9px] leading-[1.35]">{value}</p>
    </Frame>
  );
  return (
    <div className={PAGE}>
      <Header
        data={data}
        fields={[
          ["Gender", s.gender ?? ""],
          ["Age", s.age ?? ""],
          ["Height", s.height ?? ""],
          ["Weight", s.weight ?? ""],
          ["Eyes", s.eyes ?? ""],
          ["Skin", s.skin ?? ""],
          ["Hair", s.hair ?? "", "col-span-2"],
        ]}
      />
      <div className="grid h-[870px] grid-cols-[35%_1fr] gap-3">
        <div className="flex min-h-0 flex-col gap-2">
          <Frame label="Character portrait" className="h-[250px]">
            {data.portraitUrl ? <img src={data.portraitUrl} alt="" className="mx-auto h-full object-contain" /> : null}
          </Frame>
          {box("Personality traits", s.traits, "flex-1")}
          {box("Ideal", s.ideals, "flex-1")}
          {box("Bond", s.bonds, "flex-1")}
          {box("Flaw", s.flaws, "flex-1")}
          <Frame label="Background feature" className="flex-1">
            {data.backgroundFeature && <FeatureText features={[data.backgroundFeature]} />}
          </Frame>
          {box("Trinket", s.trinket, "h-[70px]")}
        </div>
        <div className="flex min-h-0 flex-col gap-2">
          <Frame label="Allies & organizations" className="h-[250px]">
            <div className="flex h-full gap-2 overflow-hidden">
              <div className="min-w-0 flex-1 overflow-hidden">
                {s.organization && <div className="mb-1 text-[11px] font-bold">{s.organization}</div>}
                <div className="whitespace-pre-line text-[9px] leading-snug">{s.allies}</div>
              </div>
              {s.organizationSymbol && <img src={s.organizationSymbol} alt="" className="h-[110px] w-[110px] shrink-0 object-contain" />}
            </div>
          </Frame>
          {box("Background story", s.backstory, "flex-[2]")}
          {box("Additional features", [s.features, s.appearance].filter(Boolean).join("\n\n"), "flex-1")}
        </div>
      </div>
      <Footer />
    </div>
  );
}

function InventoryPage({ data }: { data: SheetData }) {
  const strength = data.abilities.find((a) => a.abbreviation === "STR")?.calculatedScore ?? 10;
  const lines = (n: number) => Array.from({ length: n }, (_, i) => <div key={i} className="h-[17px] border-b border-neutral-300" />);
  return (
    <div className={PAGE}>
      <div className="grid h-[970px] grid-cols-[1fr_32%] gap-3">
        <div className="flex flex-col gap-3">
          <Frame label="Inventory — adventuring gear, arms, armor and other equipment" className="flex-[3]">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Adventuring gear</Label>
                {lines(30)}
              </div>
              <div className="flex flex-col">
                <Label>Magic items</Label>
                {lines(14)}
                <div className="mt-2 flex items-center justify-end gap-2">
                  <Label>Attuned magic items</Label>
                  <Pill>0</Pill> / <Pill>3</Pill>
                </div>
                <div className="mt-3 grid grid-cols-5 gap-1 text-center">
                  {["Copper", "Silver", "Electrum", "Gold", "Platinum"].map((c) => (
                    <div key={c}>
                      <Label>{c}</Label>
                      <Pill>0</Pill>
                    </div>
                  ))}
                </div>
                <div className="mt-3 grid grid-cols-2 gap-2 text-center">
                  <div>
                    <Label>Carry capacity</Label>
                    <Pill>{strength * 15} lb</Pill>
                  </div>
                  <div>
                    <Label>Push, drag, lift</Label>
                    <Pill>{strength * 30} lb</Pill>
                  </div>
                </div>
              </div>
            </div>
          </Frame>
          <Frame label="Additional treasure" className="flex-1" />
        </div>
        <div className="flex flex-col gap-3">
          <Frame label="Inventory — item descriptions & notes" className="flex-[3]">
            {lines(40)}
          </Frame>
          <Frame label="Quest items & trinkets" className="flex-1" />
        </div>
      </div>
      <Footer />
    </div>
  );
}

function TextPage({ title, text }: { title: string; text: string }) {
  return (
    <div className={PAGE}>
      <Frame className="h-[970px]">
        <h2 className="mb-2 text-lg font-semibold">{title}</h2>
        <div className="columns-2 gap-6 whitespace-pre-line text-[9.5px] leading-[1.45]">{text}</div>
      </Frame>
      <Footer />
    </div>
  );
}

function FeaturesPage({ features }: { features: SheetFeature[] }) {
  return (
    <div className={PAGE}>
      <Frame label="Features & traits (continued)" className="h-[970px]">
        <div className="columns-2 gap-6">
          <FeatureText features={features} />
        </div>
      </Frame>
      <Footer />
    </div>
  );
}

function SpellPage({ title, casting, spells }: { title: string; casting: SheetSpellcasting | null; spells: SheetSpell[] }) {
  const levels = [...new Set([...spells.map((s) => s.level), ...Object.keys(casting?.slots ?? {}).map(Number)])].sort((a, b) => a - b);
  return (
    <div className={PAGE}>
      <div className="mb-4 flex items-center gap-4 rounded-lg border-2 border-neutral-800 bg-neutral-100 px-4 py-3">
        <div className="flex-1 rounded-md border-2 border-neutral-800 bg-white px-3 py-2 text-center text-lg">{title}</div>
        {[
          ["Spellcasting ability", casting?.ability],
          ["Spell attack bonus", casting ? fmt(casting.attackBonus) : ""],
          ["Saving throw DC", casting?.saveDc],
          ["Spells to prepare", casting?.prepare ?? ""],
        ].map(([label, value]) => (
          <div key={label as string} className="text-center">
            <div className="min-w-20 rounded-md border-2 border-neutral-800 bg-white px-2 py-1 text-sm">{value || " "}</div>
            <Label className="mt-1">{label}</Label>
          </div>
        ))}
      </div>
      <div className="space-y-3">
        {levels.map((level) => {
          const list = spells.filter((s) => s.level === level);
          const slots = casting?.slots[level] ?? 0;
          return (
            <div key={level} className="rounded-lg border border-neutral-300 p-2">
              <div className="mb-1 flex items-center gap-3 rounded bg-neutral-400 px-2 py-0.5 text-[8px] font-semibold uppercase tracking-wider text-white">
                <span>{level === 0 ? "Cantrips" : `${["", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th"][level]} level`}</span>
                {slots > 0 && (
                  <span className="ms-auto flex items-center gap-1">
                    {slots} spell slots
                    {Array.from({ length: slots }, (_, i) => (
                      <span key={i} className="size-2 rounded-full bg-white" />
                    ))}
                  </span>
                )}
              </div>
              <div className="grid grid-cols-3 gap-x-3 gap-y-1">
                {list.map((spell) => (
                  <div key={spell.name + spell.origin} className="flex items-center gap-1.5 rounded bg-neutral-100 px-1.5 py-0.5 text-[9px]">
                    <span className="size-2 shrink-0 rounded-full border border-neutral-500" />
                    <span className="truncate">
                      {spell.name}
                      {!casting && spell.origin ? <span className="text-neutral-500"> ({spell.origin.replace(/^Level \d+: /, "")})</span> : null}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          );
        })}
      </div>
      <Footer />
    </div>
  );
}

function SpellCard({ spell }: { spell: SheetSpell }) {
  const html = DOMPurify.sanitize(spell.description, { FORBID_ATTR: ["style"] });
  return (
    <div className="flex h-[318px] flex-col overflow-hidden rounded-lg border-2 border-neutral-700 p-2">
      <div className="rounded bg-neutral-200 py-0.5 text-center text-[12px] font-semibold">{spell.name}</div>
      <div className="my-1 text-center text-[8px] italic">{spellLevelLine(spell)}</div>
      <div className="grid grid-cols-[62px_1fr] gap-x-2 gap-y-0.5 text-[8px]">
        {[
          ["Casting time", spell.time + (spell.ritual ? " (ritual)" : "")],
          ["Range", spell.range],
          ["Duration", spell.duration],
          ["Components", spell.components],
        ].map(([label, value]) => (
          <div key={label} className="contents">
            <span className="rounded-l bg-neutral-100 px-1 text-right uppercase text-neutral-500">{label}</span>
            <span className="truncate rounded-r bg-neutral-100 px-1">{value}</span>
          </div>
        ))}
      </div>
      <div className="mt-1.5 min-h-0 flex-1 overflow-hidden text-[7.5px] leading-[1.3] [&_p]:mb-1" dangerouslySetInnerHTML={{ __html: html }} />
      <div className="mt-1 flex justify-between text-[7px] italic text-neutral-600">
        <span className="truncate">{spell.origin.replace(/^Level \d+: /, "")}</span>
        <span className="truncate">{spell.source}</span>
      </div>
    </div>
  );
}

function SpellCardPages({ spells }: { spells: SheetSpell[] }) {
  const pages: SheetSpell[][] = [];
  for (let i = 0; i < spells.length; i += 9) pages.push(spells.slice(i, i + 9));
  return (
    <>
      {pages.map((page, i) => (
        <div key={i} className={PAGE}>
          <div className="grid grid-cols-3 gap-3">
            {page.map((spell) => (
              <SpellCard key={spell.name + spell.origin} spell={spell} />
            ))}
          </div>
          <Footer />
        </div>
      ))}
    </>
  );
}

export function CharacterSheetPage() {
  const { id = "" } = useParams();
  const { data, isLoading, error } = useSheetData(id);
  const [exporting, setExporting] = useState(false);

  // Aurora's own sheet templates, filled in (see lib/aurora-sheet); "view" opens it in the browser's PDF viewer
  async function makePdf(view: boolean) {
    if (!data) return;
    const tab = view ? window.open("", "_blank") : null;
    setExporting(true);
    try {
      const bytes = await buildAuroraSheet(data);
      const url = URL.createObjectURL(new Blob([bytes as BlobPart], { type: "application/pdf" }));
      if (tab) {
        tab.location.href = url;
      } else {
        const link = document.createElement("a");
        link.href = url;
        link.download = `${data.name.replace(/[^\w\- ]+/g, "").trim() || "character"}.pdf`;
        link.click();
      }
      setTimeout(() => URL.revokeObjectURL(url), 60_000);
    } catch (e) {
      tab?.close();
      toast.error("Could not make the PDF", { description: (e as Error).message });
    } finally {
      setExporting(false);
    }
  }

  if (isLoading) return <Spinner className="mx-auto my-24 size-6" />;
  if (error || !data)
    return (
      <p className="py-24 text-center text-muted-foreground">
        {(error as { status?: number } | null)?.status === 401 ? "This character's player locked their characters with a password." : "This character could not be loaded."}
      </p>
    );

  const [mainFeatures, moreFeatures] = split(data.features, 3600);
  const notes = [data.story.backstory && data.story.backstory.length > 1600 ? data.story.backstory : "", data.story.notes ?? ""].filter(Boolean).join("\n\n");
  const allSpells = [...data.spellcasting.flatMap((c) => c.spells), ...data.otherSpells].sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));

  return (
    <div className="min-h-screen bg-neutral-300 py-6 print:bg-white print:py-0">
      <div className="mx-auto mb-4 flex w-[816px] max-w-full items-center gap-2 px-4 print:hidden">
        <Button variant="secondary" asChild>
          <Link to={`/characters/${id}`}>
            <ArrowLeftIcon /> Back to the builder
          </Link>
        </Button>
        <span className="flex-1" />
        <Button variant="secondary" onClick={() => window.print()}>
          <PrinterIcon /> Print
        </Button>
        <Button variant="secondary" onClick={() => makePdf(true)} disabled={exporting}>
          <FileTextIcon /> View PDF
        </Button>
        <Button onClick={() => makePdf(false)} disabled={exporting}>
          {exporting ? <Spinner /> : <DownloadIcon />} Download PDF
        </Button>
      </div>
      <div className="overflow-x-auto">
        <MainPage data={data} features={mainFeatures} />
        {moreFeatures.length > 0 && <FeaturesPage features={moreFeatures} />}
        <DetailsPage data={data} />
        <InventoryPage data={data} />
        {notes && <TextPage title={`${data.name}: Backstory & notes`} text={notes} />}
        {data.spellcasting.map((c) => (
          <SpellPage key={c.name} title={c.name} casting={c} spells={c.spells} />
        ))}
        {data.otherSpells.length > 0 && <SpellPage title="Other Spells" casting={null} spells={data.otherSpells} />}
        {allSpells.length > 0 && <SpellCardPages spells={allSpells} />}
      </div>
    </div>
  );
}

